"""add model runs

Revision ID: 3742a91d5106
Revises: 4b93d3bcddd0
Create Date: 2026-09-25 20:57:46.701402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3742a91d5106'
down_revision: Union[str, Sequence[str], None] = '4b93d3bcddd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('ttft_ms', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_per_second', sa.Float(), nullable=True),
    sa.Column('vram_mb', sa.Float(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_mb', sa.Float(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_model'), 'model_runs', ['model'], unique=False)
    op.create_index(op.f('ix_model_runs_provider'), 'model_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_model_runs_request_type'), 'model_runs', ['request_type'], unique=False)
    op.create_index(op.f('ix_model_runs_task_id'), 'model_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_model_runs_task_type'), 'model_runs', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_runs_task_type'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_task_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_request_type'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_provider'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
