"""link conversations to sessions

Revision ID: 4b1f5dd555a8
Revises: e1b3e199ffa1
Create Date: 2026-09-25 01:05:16.477582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1f5dd555a8'
down_revision: Union[str, Sequence[str], None] = 'e1b3e199ffa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_foreign_key(
    "fk_conversations_session_id_sessions",
    "conversations",
    "sessions",
    ["session_id"],
    ["id"],
    ondelete="SET NULL",
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    "fk_conversations_session_id_sessions",
    "conversations",
    type_="foreignkey",
)
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###
