"""create context snapshots table

Revision ID: bac53152111b
Revises: dcca6dc6adc0
Create Date: 2026-09-25 01:35:47.723409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac53152111b'
down_revision: Union[str, Sequence[str], None] = 'dcca6dc6adc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_application', sa.String(length=255), nullable=True),
    sa.Column('active_project', sa.String(length=255), nullable=True),
    sa.Column('active_task', sa.String(length=255), nullable=True),
    sa.Column('relevant_context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_context_snapshots_session_id_sessions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_snapshots_session_id'), 'context_snapshots', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_context_snapshots_session_id_sessions', 'context_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_context_snapshots_session_id'), table_name='context_snapshots')
    op.drop_table('context_snapshots')
    # ### end Alembic commands ###
