"""create observations table

Revision ID: dcca6dc6adc0
Revises: 9f991d3cb4fe
Create Date: 2026-09-25 01:17:08.053047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcca6dc6adc0'
down_revision: Union[str, Sequence[str], None] = '9f991d3cb4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_observations_session_id_sessions', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_observations_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_event_type'), 'observations', ['event_type'], unique=False)
    op.create_index(op.f('ix_observations_session_id'), 'observations', ['session_id'], unique=False)
    op.create_index(op.f('ix_observations_user_id'), 'observations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_observations_user_id_users', 'observations', type_='foreignkey')
    op.drop_constraint('fk_observations_session_id_sessions', 'observations', type_='foreignkey')
    op.drop_index(op.f('ix_observations_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_session_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_event_type'), table_name='observations')
    op.drop_table('observations')
    # ### end Alembic commands ###
