"""create sessions table

Revision ID: e1b3e199ffa1
Revises: 0acd36a78d89
Create Date: 2026-09-25 00:59:06.582490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b3e199ffa1'
down_revision: Union[str, Sequence[str], None] = '0acd36a78d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(
                                ['user_id'],
                                ['users.id'],
                                name='fk_sessions_user_id_users',
                                ondelete='CASCADE',
                            ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
