"""create tool executions table

Revision ID: ef9aec353102
Revises: 735021c61e0d
Create Date: 2026-09-25 01:59:17.155715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9aec353102'
down_revision: Union[str, Sequence[str], None] = '735021c61e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name='fk_tool_executions_agent_run_id_agent_runs', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_tool_executions_task_id_tasks', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_agent_run_id'), 'tool_executions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_status'), 'tool_executions', ['status'], unique=False)
    op.create_index(op.f('ix_tool_executions_task_id'), 'tool_executions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tool_executions_task_id_tasks', 'tool_executions', type_='foreignkey')
    op.drop_constraint('fk_tool_executions_agent_run_id_agent_runs', 'tool_executions', type_='foreignkey')
    op.drop_index(op.f('ix_tool_executions_task_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_status'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_agent_run_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###
